### ISSUE TITLE
Refactor and clarify webcam code

### ISSUE THREAD

**Issue by jgottula** [bgottula/track#39]
- [x] Move the camera-related junk into a nested class in `OpticalErrorSource`
- [ ] Rename all of the "camera" references to "webcam" or something similar, to clarify the distinction between the OpenCV guide camera (webcam) and the actual imaging camera (DSLR)

**Comment by bgottula** [comment]
I grepped for "camera" in the entire project and found that it only shows up in docstring comments (mostly in errorsources.py) and as program arguments to optical_track and hybrid_track. I'm okay with leaving those names as-is because at least for the time being the only camera this project interfaces with is the guidescope camera. If there are naming conflicts in the future we can deal with them at that time.
